const products = [
    {
        productId: 'P001',
        productName: 'Men’s Casual T-Shirt',
        image: 'tshirt-image.jpg',
        category: 'T-Shirts',
        price: 29.99,
        discount: 10, // 10% discount
        stock: 150,
        status: 'Active',
        dateAdded: '2024-08-15',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Red', 'Blue', 'Black'],
    },
    {
        productId: 'P002',
        productName: 'Women’s Denim Jacket',
        image: 'denim-jacket.jpg',
        category: 'Jackets',
        price: 79.99,
        discount: 0, // No discount
        stock: 75,
        status: 'Active',
        dateAdded: '2024-07-20',
        sizes: ['S', 'M', 'L'],
        colors: ['Denim Blue', 'Black'],
    },
    {
        productId: 'P003',
        productName: 'Men’s Slim Fit Jeans',
        image: 'slim-fit-jeans.jpg',
        category: 'Jeans',
        price: 49.99,
        discount: 15, // 15% discount
        stock: 100,
        status: 'Active',
        dateAdded: '2024-09-01',
        sizes: ['M', 'L', 'XL'],
        colors: ['Blue', 'Dark Blue', 'Black'],
    },
    {
        productId: 'P004',
        productName: 'Women’s Summer Dress',
        image: 'summer-dress.jpg',
        category: 'Dresses',
        price: 59.99,
        discount: 5, // 5% discount
        stock: 50,
        status: 'Out of Stock',
        dateAdded: '2024-06-10',
        sizes: ['S', 'M', 'L'],
        colors: ['Floral', 'Pink'],
    },
    {
        productId: 'P005',
        productName: 'Unisex Hoodie',
        image: 'hoodie.jpg',
        category: 'Hoodies',
        price: 39.99,
        discount: 20, // 20% discount
        stock: 200,
        status: 'Active',
        dateAdded: '2024-09-15',
        sizes: ['M', 'L', 'XL', 'XXL'],
        colors: ['Gray', 'Black', 'White'],
    },{
        productId: 'P005',
        productName: 'Unisex Hoodie',
        image: 'hoodie.jpg',
        category: 'Hoodies',
        price: 39.99,
        discount: 20, // 20% discount
        stock: 200,
        status: 'Active',
        dateAdded: '2024-09-15',
        sizes: ['M', 'L', 'XL', 'XXL'],
        colors: ['Gray', 'Black', 'White'],
    },{
        productId: 'P005',
        productName: 'Unisex Hoodie',
        image: 'hoodie.jpg',
        category: 'Hoodies',
        price: 39.99,
        discount: 20, // 20% discount
        stock: 200,
        status: 'Active',
        dateAdded: '2024-09-15',
        sizes: ['M', 'L', 'XL', 'XXL'],
        colors: ['Gray', 'Black', 'White'],
    },{
        productId: 'P005',
        productName: 'Unisex Hoodie',
        image: 'hoodie.jpg',
        category: 'Hoodies',
        price: 39.99,
        discount: 20, // 20% discount
        stock: 200,
        status: 'Active',
        dateAdded: '2024-09-15',
        sizes: ['M', 'L', 'XL', 'XXL'],
        colors: ['Gray', 'Black', 'White'],
    },
    {
        productId: 'P005',
        productName: 'Unisex Hoodie',
        image: 'hoodie.jpg',
        category: 'Hoodies',
        price: 39.99,
        discount: 20, // 20% discount
        stock: 200,
        status: 'Active',
        dateAdded: '2024-09-15',
        sizes: ['M', 'L', 'XL', 'XXL'],
        colors: ['Gray', 'Black', 'White'],
    },
    {
        productId: 'P005',
        productName: 'Unisex Hoodie',
        image: 'hoodie.jpg',
        category: 'Hoodies',
        price: 39.99,
        discount: 20, // 20% discount
        stock: 200,
        status: 'Active',
        dateAdded: '2024-09-15',
        sizes: ['M', 'L', 'XL', 'XXL'],
        colors: ['Gray', 'Black', 'White'],
    },
    {
        productId: 'P005',
        productName: 'Unisex Hoodie',
        image: 'hoodie.jpg',
        category: 'Hoodies',
        price: 39.99,
        discount: 20, // 20% discount
        stock: 200,
        status: 'Active',
        dateAdded: '2024-09-15',
        sizes: ['M', 'L', 'XL', 'XXL'],
        colors: ['Gray', 'Black', 'White'],
    },

];

export default products